name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has not had activity for 30 days. It will be automatically closed in 30 days.'
          stale-pr-message: 'This PR has not had activity for 30 days. It will be automatically closed in 30 days.'
          exempt-issue-labels: 'bug,enhancement,feature-request,help-wanted,upstream'
          exempt-pr-labels: 'bug,enhancement,feature-request,help-wanted,upstream'
          exempt-draft-pr: true
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 120
          days-before-close: 30
          remove-stale-when-updated: true

permissions:
  issues: write
  pull-requests: write
