name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has not had activity for 30 days. It will be automatically closed in 7 days.'
          stale-pr-message: 'This PR has not had activity for 30 days. It will be automatically closed in 7 days.'
          exempt-issue-labels: 'bug,enhancement,feature-request,help-wanted,upstream'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 30
          days-before-close: 7
